var annotated_dup =
[
    [ "nlohmann", "namespacenlohmann.html", [
      [ "adl_serializer< Chat >", "structnlohmann_1_1adl__serializer_3_01Chat_01_4.html", "structnlohmann_1_1adl__serializer_3_01Chat_01_4" ],
      [ "adl_serializer< ChatMember >", "structnlohmann_1_1adl__serializer_3_01ChatMember_01_4.html", "structnlohmann_1_1adl__serializer_3_01ChatMember_01_4" ],
      [ "adl_serializer< Message >", "structnlohmann_1_1adl__serializer_3_01Message_01_4.html", "structnlohmann_1_1adl__serializer_3_01Message_01_4" ],
      [ "adl_serializer< MessageStatus >", "structnlohmann_1_1adl__serializer_3_01MessageStatus_01_4.html", "structnlohmann_1_1adl__serializer_3_01MessageStatus_01_4" ],
      [ "adl_serializer< PrivateChat >", "structnlohmann_1_1adl__serializer_3_01PrivateChat_01_4.html", "structnlohmann_1_1adl__serializer_3_01PrivateChat_01_4" ],
      [ "adl_serializer< Reaction >", "structnlohmann_1_1adl__serializer_3_01Reaction_01_4.html", "structnlohmann_1_1adl__serializer_3_01Reaction_01_4" ],
      [ "adl_serializer< ReactionInfo >", "structnlohmann_1_1adl__serializer_3_01ReactionInfo_01_4.html", "structnlohmann_1_1adl__serializer_3_01ReactionInfo_01_4" ],
      [ "adl_serializer< RequestDTO >", "structnlohmann_1_1adl__serializer_3_01RequestDTO_01_4.html", "structnlohmann_1_1adl__serializer_3_01RequestDTO_01_4" ],
      [ "adl_serializer< User >", "structnlohmann_1_1adl__serializer_3_01User_01_4.html", "structnlohmann_1_1adl__serializer_3_01User_01_4" ],
      [ "adl_serializer< UserChat >", "structnlohmann_1_1adl__serializer_3_01UserChat_01_4.html", "structnlohmann_1_1adl__serializer_3_01UserChat_01_4" ],
      [ "adl_serializer< UserCredentials >", "structnlohmann_1_1adl__serializer_3_01UserCredentials_01_4.html", "structnlohmann_1_1adl__serializer_3_01UserCredentials_01_4" ],
      [ "adl_serializer< UserMessage >", "structnlohmann_1_1adl__serializer_3_01UserMessage_01_4.html", "structnlohmann_1_1adl__serializer_3_01UserMessage_01_4" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< ReactionInfo >", "structstd_1_1hash_3_01ReactionInfo_01_4.html", "structstd_1_1hash_3_01ReactionInfo_01_4" ]
    ] ],
    [ "Test", "namespaceTest.html", [
      [ "TestFixture", "structTest_1_1TestFixture.html", "structTest_1_1TestFixture" ]
    ] ],
    [ "TestChatManager", "namespaceTestChatManager.html", [
      [ "TestFixture", "structTestChatManager_1_1TestFixture.html", "structTestChatManager_1_1TestFixture" ]
    ] ],
    [ "AuthController", "classAuthController.html", "classAuthController" ],
    [ "AuthManager", "classAuthManager.html", "classAuthManager" ],
    [ "AuthMiddleware", "structAuthMiddleware.html", "structAuthMiddleware" ],
    [ "AuthResponce", "structAuthResponce.html", "structAuthResponce" ],
    [ "BaseManager", "classBaseManager.html", "classBaseManager" ],
    [ "BenchmarkGatewayServerFixrute", "structBenchmarkGatewayServerFixrute.html", "structBenchmarkGatewayServerFixrute" ],
    [ "Builder", "structBuilder.html", "structBuilder" ],
    [ "Builder< Chat >", "structBuilder_3_01Chat_01_4.html", "structBuilder_3_01Chat_01_4" ],
    [ "Builder< ChatMember >", "structBuilder_3_01ChatMember_01_4.html", "structBuilder_3_01ChatMember_01_4" ],
    [ "Builder< Message >", "structBuilder_3_01Message_01_4.html", "structBuilder_3_01Message_01_4" ],
    [ "Builder< MessageStatus >", "structBuilder_3_01MessageStatus_01_4.html", "structBuilder_3_01MessageStatus_01_4" ],
    [ "Builder< PrivateChat >", "structBuilder_3_01PrivateChat_01_4.html", "structBuilder_3_01PrivateChat_01_4" ],
    [ "Builder< Reaction >", "structBuilder_3_01Reaction_01_4.html", "structBuilder_3_01Reaction_01_4" ],
    [ "Builder< ReactionInfo >", "structBuilder_3_01ReactionInfo_01_4.html", "structBuilder_3_01ReactionInfo_01_4" ],
    [ "Builder< User >", "structBuilder_3_01User_01_4.html", "structBuilder_3_01User_01_4" ],
    [ "Builder< UserCredentials >", "structBuilder_3_01UserCredentials_01_4.html", "structBuilder_3_01UserCredentials_01_4" ],
    [ "CacheKeyGenerator", "classCacheKeyGenerator.html", "classCacheKeyGenerator" ],
    [ "CacheMiddleware", "structCacheMiddleware.html", "structCacheMiddleware" ],
    [ "CharConfig", "structCharConfig.html", "structCharConfig" ],
    [ "Chat", "structChat.html", "structChat" ],
    [ "ChatBase", "structChatBase.html", "structChatBase" ],
    [ "ChatController", "classChatController.html", "classChatController" ],
    [ "ChatDrawData", "structChatDrawData.html", "structChatDrawData" ],
    [ "ChatFactory", "classChatFactory.html", "classChatFactory" ],
    [ "ChatItemDelegate", "classChatItemDelegate.html", "classChatItemDelegate" ],
    [ "ChatItemStyle", "structChatItemStyle.html", "structChatItemStyle" ],
    [ "ChatManager", "classChatManager.html", "classChatManager" ],
    [ "ChatMember", "structChatMember.html", "structChatMember" ],
    [ "ChatModel", "classChatModel.html", "classChatModel" ],
    [ "ChatNetworkManager", "classChatNetworkManager.html", "classChatNetworkManager" ],
    [ "ChatServer", "classChatServer.html", "classChatServer" ],
    [ "ChatUseCase", "classChatUseCase.html", "classChatUseCase" ],
    [ "ClickOutsideClosableListView", "classClickOutsideClosableListView.html", "classClickOutsideClosableListView" ],
    [ "CompileTimeError", "structCompileTimeError.html", null ],
    [ "CompileTimeError< true >", "structCompileTimeError_3_01true_01_4.html", null ],
    [ "Config", "structConfig.html", "structConfig" ],
    [ "ContractViolation", "structContractViolation.html", "structContractViolation" ],
    [ "ContractViolationError", "classContractViolationError.html", "classContractViolationError" ],
    [ "Controller", "classController.html", "classController" ],
    [ "CrowSocket", "classCrowSocket.html", "classCrowSocket" ],
    [ "DarkTheme", "classDarkTheme.html", "classDarkTheme" ],
    [ "DataManager", "classDataManager.html", "classDataManager" ],
    [ "DelegatorsFactory", "classDelegatorsFactory.html", "classDelegatorsFactory" ],
    [ "DeleteMessageHandler", "classDeleteMessageHandler.html", "classDeleteMessageHandler" ],
    [ "DeleteMessageReactionHandler", "classDeleteMessageReactionHandler.html", "classDeleteMessageReactionHandler" ],
    [ "DeleteQuery", "classDeleteQuery.html", "classDeleteQuery" ],
    [ "DeleteResult", "structDeleteResult.html", "structDeleteResult" ],
    [ "DummyParentCtx", "structDummyParentCtx.html", "structDummyParentCtx" ],
    [ "EntityFields", "structEntityFields.html", null ],
    [ "EntityFields< Chat >", "structEntityFields_3_01Chat_01_4.html", "structEntityFields_3_01Chat_01_4" ],
    [ "EntityFields< ChatMember >", "structEntityFields_3_01ChatMember_01_4.html", "structEntityFields_3_01ChatMember_01_4" ],
    [ "EntityFields< Message >", "structEntityFields_3_01Message_01_4.html", "structEntityFields_3_01Message_01_4" ],
    [ "EntityFields< MessageStatus >", "structEntityFields_3_01MessageStatus_01_4.html", "structEntityFields_3_01MessageStatus_01_4" ],
    [ "EntityFields< PrivateChat >", "structEntityFields_3_01PrivateChat_01_4.html", "structEntityFields_3_01PrivateChat_01_4" ],
    [ "EntityFields< Reaction >", "structEntityFields_3_01Reaction_01_4.html", "structEntityFields_3_01Reaction_01_4" ],
    [ "EntityFields< ReactionInfo >", "structEntityFields_3_01ReactionInfo_01_4.html", "structEntityFields_3_01ReactionInfo_01_4" ],
    [ "EntityFields< User >", "structEntityFields_3_01User_01_4.html", "structEntityFields_3_01User_01_4" ],
    [ "EntityFields< UserCredentials >", "structEntityFields_3_01UserCredentials_01_4.html", "structEntityFields_3_01UserCredentials_01_4" ],
    [ "EntityKey", "structEntityKey.html", "structEntityKey" ],
    [ "EntityKey< ChatMember >", "structEntityKey_3_01ChatMember_01_4.html", "structEntityKey_3_01ChatMember_01_4" ],
    [ "EntityKey< MessageStatus >", "structEntityKey_3_01MessageStatus_01_4.html", "structEntityKey_3_01MessageStatus_01_4" ],
    [ "EntityKey< PrivateChat >", "structEntityKey_3_01PrivateChat_01_4.html", "structEntityKey_3_01PrivateChat_01_4" ],
    [ "EntityKey< Reaction >", "structEntityKey_3_01Reaction_01_4.html", "structEntityKey_3_01Reaction_01_4" ],
    [ "EntityKey< UserCredentials >", "structEntityKey_3_01UserCredentials_01_4.html", "structEntityKey_3_01UserCredentials_01_4" ],
    [ "FakeSocket", "classFakeSocket.html", "classFakeSocket" ],
    [ "FakeSqlExecutor", "classFakeSqlExecutor.html", "classFakeSqlExecutor" ],
    [ "FastBuilder", "structFastBuilder.html", "structFastBuilder" ],
    [ "FastEntityBuilder", "classFastEntityBuilder.html", "classFastEntityBuilder" ],
    [ "Field", "structField.html", "structField" ],
    [ "FixedHeightDelegate", "classFixedHeightDelegate.html", "classFixedHeightDelegate" ],
    [ "ForwardRequestDTO", "structForwardRequestDTO.html", "structForwardRequestDTO" ],
    [ "GatewayController", "classGatewayController.html", "classGatewayController" ],
    [ "GatewayMetrics", "classGatewayMetrics.html", "classGatewayMetrics" ],
    [ "GatewayServer", "classGatewayServer.html", "classGatewayServer" ],
    [ "GeneratorId", "classGeneratorId.html", "classGeneratorId" ],
    [ "GenericFastEntityBuilder", "classGenericFastEntityBuilder.html", "classGenericFastEntityBuilder" ],
    [ "GenericRepository", "classGenericRepository.html", "classGenericRepository" ],
    [ "GetMessagePack", "structGetMessagePack.html", "structGetMessagePack" ],
    [ "GroupChat", "structGroupChat.html", "structGroupChat" ],
    [ "IActiveSocketRepository", "classIActiveSocketRepository.html", "classIActiveSocketRepository" ],
    [ "IAuthManager", "classIAuthManager.html", "classIAuthManager" ],
    [ "IAuthoritizer", "classIAuthoritizer.html", "classIAuthoritizer" ],
    [ "IBaseQuery", "classIBaseQuery.html", "classIBaseQuery" ],
    [ "ICache", "classICache.html", "classICache" ],
    [ "ICacheService", "classICacheService.html", "classICacheService" ],
    [ "IChatDataManager", "classIChatDataManager.html", "classIChatDataManager" ],
    [ "IChatJsonService", "classIChatJsonService.html", "classIChatJsonService" ],
    [ "IChatManager", "classIChatManager.html", "classIChatManager" ],
    [ "IChatNetworkManager", "classIChatNetworkManager.html", "classIChatNetworkManager" ],
    [ "IClient", "classIClient.html", "classIClient" ],
    [ "IDataBase", "classIDataBase.html", "classIDataBase" ],
    [ "IdField", "structIdField.html", "structIdField" ],
    [ "IEntityBuilder", "classIEntityBuilder.html", "classIEntityBuilder" ],
    [ "IEventBus", "classIEventBus.html", "classIEventBus" ],
    [ "IEventBusLifecycle", "classIEventBusLifecycle.html", "classIEventBusLifecycle" ],
    [ "IEventPublisher", "classIEventPublisher.html", "classIEventPublisher" ],
    [ "IEventSubscriber", "classIEventSubscriber.html", "classIEventSubscriber" ],
    [ "IGenerator", "classIGenerator.html", "classIGenerator" ],
    [ "IIdGenerator", "classIIdGenerator.html", "classIIdGenerator" ],
    [ "IMainWindow", "classIMainWindow.html", "classIMainWindow" ],
    [ "IMessageCommandService", "classIMessageCommandService.html", "classIMessageCommandService" ],
    [ "IMessageDataManager", "classIMessageDataManager.html", "classIMessageDataManager" ],
    [ "IMessageHandler", "classIMessageHandler.html", "classIMessageHandler" ],
    [ "IMessageJsonService", "classIMessageJsonService.html", "classIMessageJsonService" ],
    [ "IMessageNetworkManager", "classIMessageNetworkManager.html", "classIMessageNetworkManager" ],
    [ "IMessageQueryService", "classIMessageQueryService.html", "classIMessageQueryService" ],
    [ "IMessageStatusDataManager", "classIMessageStatusDataManager.html", "classIMessageStatusDataManager" ],
    [ "IMessageStatusJsonService", "classIMessageStatusJsonService.html", "classIMessageStatusJsonService" ],
    [ "IMetrics", "classIMetrics.html", "classIMetrics" ],
    [ "INetworkAccessManager", "classINetworkAccessManager.html", "classINetworkAccessManager" ],
    [ "INetworkFacade", "classINetworkFacade.html", "classINetworkFacade" ],
    [ "InitMessageHandler", "classInitMessageHandler.html", "classInitMessageHandler" ],
    [ "INotifier", "classINotifier.html", "classINotifier" ],
    [ "IOutboxWorker", "classIOutboxWorker.html", "classIOutboxWorker" ],
    [ "IPublisher", "classIPublisher.html", "classIPublisher" ],
    [ "IQuery", "structIQuery.html", "structIQuery" ],
    [ "IRateLimiter", "classIRateLimiter.html", "classIRateLimiter" ],
    [ "IReactionDataManager", "classIReactionDataManager.html", "classIReactionDataManager" ],
    [ "IReactionInfoJsonService", "classIReactionInfoJsonService.html", "classIReactionInfoJsonService" ],
    [ "IReactionJsonService", "classIReactionJsonService.html", "classIReactionJsonService" ],
    [ "is_in_variant", "structis__in__variant.html", null ],
    [ "is_in_variant< V, std::variant< Ts... > >", "structis__in__variant_3_01V_00_01std_1_1variant_3_01Ts_8_8_8_01_4_01_4.html", null ],
    [ "ISocket", "classISocket.html", "classISocket" ],
    [ "ISocketResponceHandler", "classISocketResponceHandler.html", "classISocketResponceHandler" ],
    [ "ISqlExecutor", "classISqlExecutor.html", "classISqlExecutor" ],
    [ "ISubscriber", "classISubscriber.html", "classISubscriber" ],
    [ "ITheme", "classITheme.html", "classITheme" ],
    [ "IThreadPool", "structIThreadPool.html", "structIThreadPool" ],
    [ "IUserDataManager", "classIUserDataManager.html", "classIUserDataManager" ],
    [ "IUserJsonService", "classIUserJsonService.html", "classIUserJsonService" ],
    [ "IUserNetworkManager", "classIUserNetworkManager.html", "classIUserNetworkManager" ],
    [ "IUserSocketRepository", "classIUserSocketRepository.html", "classIUserSocketRepository" ],
    [ "IVerifier", "classIVerifier.html", "classIVerifier" ],
    [ "JsonService", "classJsonService.html", "classJsonService" ],
    [ "JwtAuthoritizer", "classJwtAuthoritizer.html", "classJwtAuthoritizer" ],
    [ "JwtGenerator", "classJwtGenerator.html", "classJwtGenerator" ],
    [ "JWTVerifier", "classJWTVerifier.html", "classJWTVerifier" ],
    [ "LightTheme", "classLightTheme.html", "classLightTheme" ],
    [ "LoggingMiddleware", "structLoggingMiddleware.html", "structLoggingMiddleware" ],
    [ "LoginRequest", "structLoginRequest.html", "structLoginRequest" ],
    [ "LogInRequest", "structLogInRequest.html", "structLogInRequest" ],
    [ "MainWindow", "classMainWindow.html", "classMainWindow" ],
    [ "MarkReadMessageHandler", "classMarkReadMessageHandler.html", "classMarkReadMessageHandler" ],
    [ "Message", "structMessage.html", "structMessage" ],
    [ "MessageActionPanel", "classMessageActionPanel.html", "classMessageActionPanel" ],
    [ "MessageCommandManager", "classMessageCommandManager.html", "classMessageCommandManager" ],
    [ "MessageDelegate", "classMessageDelegate.html", "classMessageDelegate" ],
    [ "MessageFactory", "classMessageFactory.html", "classMessageFactory" ],
    [ "MessageListView", "classMessageListView.html", "classMessageListView" ],
    [ "MessageManager", "classMessageManager.html", "classMessageManager" ],
    [ "MessageModel", "classMessageModel.html", "classMessageModel" ],
    [ "MessageNetworkManager", "classMessageNetworkManager.html", "classMessageNetworkManager" ],
    [ "MessageQueryManager", "classMessageQueryManager.html", "classMessageQueryManager" ],
    [ "MessageStatus", "structMessageStatus.html", "structMessageStatus" ],
    [ "MessageToken", "structMessageToken.html", "structMessageToken" ],
    [ "MessageUseCase", "classMessageUseCase.html", "classMessageUseCase" ],
    [ "Meta", "structMeta.html", "structMeta" ],
    [ "MetaEntityBuilder", "classMetaEntityBuilder.html", "classMetaEntityBuilder" ],
    [ "MetricsMiddleware", "structMetricsMiddleware.html", "structMetricsMiddleware" ],
    [ "MetricsTracker", "structMetricsTracker.html", "structMetricsTracker" ],
    [ "MockApiCache", "classMockApiCache.html", "classMockApiCache" ],
    [ "MockAuthManager", "classMockAuthManager.html", "classMockAuthManager" ],
    [ "MockAutoritizer", "classMockAutoritizer.html", "classMockAutoritizer" ],
    [ "MockCache", "classMockCache.html", "classMockCache" ],
    [ "MockChatManager", "classMockChatManager.html", "classMockChatManager" ],
    [ "MockChatNetworkManager", "classMockChatNetworkManager.html", "classMockChatNetworkManager" ],
    [ "MockClient", "structMockClient.html", "structMockClient" ],
    [ "MockDatabase", "classMockDatabase.html", "classMockDatabase" ],
    [ "MockFacade", "classMockFacade.html", "classMockFacade" ],
    [ "MockHandler", "classMockHandler.html", "classMockHandler" ],
    [ "MockIdGenerator", "structMockIdGenerator.html", "structMockIdGenerator" ],
    [ "MockMainWindow", "classMockMainWindow.html", "classMockMainWindow" ],
    [ "MockMessageListView", "classMockMessageListView.html", "classMockMessageListView" ],
    [ "MockMessageNetworkManager", "classMockMessageNetworkManager.html", "classMockMessageNetworkManager" ],
    [ "MockMetrics", "classMockMetrics.html", "classMockMetrics" ],
    [ "MockNetworkAccessManager", "classMockNetworkAccessManager.html", "classMockNetworkAccessManager" ],
    [ "MockNotifier", "classMockNotifier.html", "classMockNotifier" ],
    [ "MockPublisher", "classMockPublisher.html", "classMockPublisher" ],
    [ "MockQuery", "classMockQuery.html", "classMockQuery" ],
    [ "MockRabitMQClient", "classMockRabitMQClient.html", "classMockRabitMQClient" ],
    [ "MockRateLimiter", "classMockRateLimiter.html", "classMockRateLimiter" ],
    [ "MockReply", "classMockReply.html", "classMockReply" ],
    [ "MockSocket", "classMockSocket.html", "classMockSocket" ],
    [ "MockThreadPool", "classMockThreadPool.html", "classMockThreadPool" ],
    [ "MockTokenGenerator", "classMockTokenGenerator.html", "classMockTokenGenerator" ],
    [ "MockUserNetworkManager", "classMockUserNetworkManager.html", "classMockUserNetworkManager" ],
    [ "MockUserSocketRepository", "classMockUserSocketRepository.html", "classMockUserSocketRepository" ],
    [ "MockVerifier", "classMockVerifier.html", "classMockVerifier" ],
    [ "Model", "classModel.html", "classModel" ],
    [ "NetworkAccessManager", "classNetworkAccessManager.html", "classNetworkAccessManager" ],
    [ "NetworkFacade", "classNetworkFacade.html", "classNetworkFacade" ],
    [ "NewMessageHandler", "classNewMessageHandler.html", "classNewMessageHandler" ],
    [ "NotificationOrchestrator", "classNotificationOrchestrator.html", "classNotificationOrchestrator" ],
    [ "NotificationOrchestratorTestFixture", "structNotificationOrchestratorTestFixture.html", "structNotificationOrchestratorTestFixture" ],
    [ "OpenSocketHandler", "classOpenSocketHandler.html", "classOpenSocketHandler" ],
    [ "OutboxWorker", "classOutboxWorker.html", "classOutboxWorker" ],
    [ "OutsideClickFilter", "classOutsideClickFilter.html", "classOutsideClickFilter" ],
    [ "Presenter", "classPresenter.html", "classPresenter" ],
    [ "PrivateChat", "structPrivateChat.html", "structPrivateChat" ],
    [ "ProxyClient", "classProxyClient.html", "classProxyClient" ],
    [ "PublishRequest", "structPublishRequest.html", "structPublishRequest" ],
    [ "QueryFactory", "classQueryFactory.html", "classQueryFactory" ],
    [ "QueuePublisher", "classQueuePublisher.html", "classQueuePublisher" ],
    [ "QueueSubscriber", "classQueueSubscriber.html", "classQueueSubscriber" ],
    [ "RabbitMQClient", "classRabbitMQClient.html", "classRabbitMQClient" ],
    [ "RabbitMQConfig", "structRabbitMQConfig.html", "structRabbitMQConfig" ],
    [ "RabbitNotificationPublisher", "classRabbitNotificationPublisher.html", "classRabbitNotificationPublisher" ],
    [ "RabbitNotificationSubscriber", "classRabbitNotificationSubscriber.html", "classRabbitNotificationSubscriber" ],
    [ "RabitMQSubscriberTester", "classRabitMQSubscriberTester.html", "classRabitMQSubscriberTester" ],
    [ "RateLimiter", "classRateLimiter.html", "classRateLimiter" ],
    [ "RateLimitMiddleware", "structRateLimitMiddleware.html", "structRateLimitMiddleware" ],
    [ "Reaction", "structReaction.html", "structReaction" ],
    [ "ReactionHitBox", "structReactionHitBox.html", "structReactionHitBox" ],
    [ "ReactionInfo", "structReactionInfo.html", "structReactionInfo" ],
    [ "ReadMessageHandler", "classReadMessageHandler.html", "classReadMessageHandler" ],
    [ "RealAuthoritizer", "classRealAuthoritizer.html", "classRealAuthoritizer" ],
    [ "RealHttpClient", "classRealHttpClient.html", "classRealHttpClient" ],
    [ "RealSocket", "classRealSocket.html", "classRealSocket" ],
    [ "RedisCache", "classRedisCache.html", "classRedisCache" ],
    [ "RedisClient", "classRedisClient.html", "classRedisClient" ],
    [ "Reflection", "structReflection.html", "structReflection" ],
    [ "Reflection< Chat >", "structReflection_3_01Chat_01_4.html", "structReflection_3_01Chat_01_4" ],
    [ "Reflection< ChatMember >", "structReflection_3_01ChatMember_01_4.html", "structReflection_3_01ChatMember_01_4" ],
    [ "Reflection< Message >", "structReflection_3_01Message_01_4.html", "structReflection_3_01Message_01_4" ],
    [ "Reflection< MessageStatus >", "structReflection_3_01MessageStatus_01_4.html", "structReflection_3_01MessageStatus_01_4" ],
    [ "Reflection< PrivateChat >", "structReflection_3_01PrivateChat_01_4.html", "structReflection_3_01PrivateChat_01_4" ],
    [ "Reflection< Reaction >", "structReflection_3_01Reaction_01_4.html", "structReflection_3_01Reaction_01_4" ],
    [ "Reflection< ReactionInfo >", "structReflection_3_01ReactionInfo_01_4.html", "structReflection_3_01ReactionInfo_01_4" ],
    [ "Reflection< User >", "structReflection_3_01User_01_4.html", "structReflection_3_01User_01_4" ],
    [ "Reflection< UserCredentials >", "structReflection_3_01UserCredentials_01_4.html", "structReflection_3_01UserCredentials_01_4" ],
    [ "RegisterRequest", "structRegisterRequest.html", "structRegisterRequest" ],
    [ "RequestDTO", "structRequestDTO.html", "structRequestDTO" ],
    [ "RetryOptions", "structRetryOptions.html", "structRetryOptions" ],
    [ "SaveMessageReactionHandler", "classSaveMessageReactionHandler.html", "classSaveMessageReactionHandler" ],
    [ "ScopedTimer", "classScopedTimer.html", "classScopedTimer" ],
    [ "SecondTestController", "classSecondTestController.html", "classSecondTestController" ],
    [ "SelectQuery", "classSelectQuery.html", "classSelectQuery" ],
    [ "SelectResult", "structSelectResult.html", "structSelectResult" ],
    [ "SendMessageHandler", "classSendMessageHandler.html", "classSendMessageHandler" ],
    [ "Server", "classServer.html", "classServer" ],
    [ "SessionManager", "classSessionManager.html", "classSessionManager" ],
    [ "SessionUseCase", "classSessionUseCase.html", "classSessionUseCase" ],
    [ "SharedFixture", "structSharedFixture.html", "structSharedFixture" ],
    [ "SignUpRequest", "structSignUpRequest.html", "structSignUpRequest" ],
    [ "SocketHandlerRegistry", "classSocketHandlerRegistry.html", "classSocketHandlerRegistry" ],
    [ "SocketHandlersRepository", "classSocketHandlersRepository.html", "classSocketHandlersRepository" ],
    [ "SocketManager", "classSocketManager.html", "classSocketManager" ],
    [ "SocketNotifier", "classSocketNotifier.html", "classSocketNotifier" ],
    [ "SocketNotifierTestFixture", "structSocketNotifierTestFixture.html", "structSocketNotifierTestFixture" ],
    [ "SocketRepository", "classSocketRepository.html", "classSocketRepository" ],
    [ "SocketUseCase", "classSocketUseCase.html", "classSocketUseCase" ],
    [ "SqlBuilder", "classSqlBuilder.html", "classSqlBuilder" ],
    [ "SqlExecutor", "classSqlExecutor.html", "classSqlExecutor" ],
    [ "SqlExecutorResult", "structSqlExecutorResult.html", "structSqlExecutorResult" ],
    [ "SQLiteDatabase", "classSQLiteDatabase.html", "classSQLiteDatabase" ],
    [ "SQLiteQuery", "classSQLiteQuery.html", "classSQLiteQuery" ],
    [ "SqlStatement", "structSqlStatement.html", "structSqlStatement" ],
    [ "SubscribeRequest", "structSubscribeRequest.html", "structSubscribeRequest" ],
    [ "TestAuthManager", "structTestAuthManager.html", "structTestAuthManager" ],
    [ "TestAuthManagerFixture", "structTestAuthManagerFixture.html", "structTestAuthManagerFixture" ],
    [ "TestAuthManagerProtectedFixture", "structTestAuthManagerProtectedFixture.html", "structTestAuthManagerProtectedFixture" ],
    [ "TestChatItemDelegate", "structTestChatItemDelegate.html", "structTestChatItemDelegate" ],
    [ "TestChatManager", "classTestChatManager.html", "classTestChatManager" ],
    [ "TestController", "classTestController.html", "classTestController" ],
    [ "TestDataManager", "structTestDataManager.html", "structTestDataManager" ],
    [ "TestGatewayMiddlewaresFixrute", "structTestGatewayMiddlewaresFixrute.html", "structTestGatewayMiddlewaresFixrute" ],
    [ "TestGatewayServerFixrute", "structTestGatewayServerFixrute.html", "structTestGatewayServerFixrute" ],
    [ "TestMessageManager", "classTestMessageManager.html", "classTestMessageManager" ],
    [ "TestProtectedAuthManager", "structTestProtectedAuthManager.html", "structTestProtectedAuthManager" ],
    [ "TestSessionManager", "classTestSessionManager.html", "classTestSessionManager" ],
    [ "TestSqliteDatabase", "structTestSqliteDatabase.html", "structTestSqliteDatabase" ],
    [ "TestUserManager", "classTestUserManager.html", "classTestUserManager" ],
    [ "ThreadPool", "classThreadPool.html", "classThreadPool" ],
    [ "TokenFactory", "structTokenFactory.html", "structTokenFactory" ],
    [ "TokenManager", "classTokenManager.html", "classTokenManager" ],
    [ "UseCaseRepository", "classUseCaseRepository.html", "classUseCaseRepository" ],
    [ "User", "structUser.html", "structUser" ],
    [ "UserChat", "structUserChat.html", "structUserChat" ],
    [ "UserCredentials", "structUserCredentials.html", "structUserCredentials" ],
    [ "UserDelegate", "classUserDelegate.html", "classUserDelegate" ],
    [ "UserDrawData", "structUserDrawData.html", "structUserDrawData" ],
    [ "UserManager", "classUserManager.html", "classUserManager" ],
    [ "UserMessage", "structUserMessage.html", "structUserMessage" ],
    [ "UserModel", "classUserModel.html", "classUserModel" ],
    [ "UserNetworkManager", "classUserNetworkManager.html", "classUserNetworkManager" ],
    [ "UserUseCase", "classUserUseCase.html", "classUserUseCase" ],
    [ "ValidationResult", "structValidationResult.html", "structValidationResult" ],
    [ "WebSocketBridge", "classWebSocketBridge.html", "classWebSocketBridge" ]
];