@startuml

node "User Device\n(Desktop)" {
  artifact "Frontend"
}

node "API Gateway" {
  artifact "Gateway Service"
}

node "Auth Service Cluster" {
  artifact "Auth Service"
}

node "Chat Service Cluster" {
  artifact "Chat Service"
}

node "Message Service Cluster" {
  artifact "Message Service"
}

node "Notification Service Cluster" {
  artifact "Notification Service"
}

node "Database Server" {
  artifact "Auth DB"
  artifact "Chat DB"
  artifact "Message DB"
}

node "Cache Server" {
  artifact "Redis"
}

node "Message Broker" {
  artifact "RabbitMQ"
}

"Frontend" --> "Gateway Service" : HTTPS / WebSocket
"Gateway Service" --> "Auth Service" : HTTP
"Gateway Service" --> "Chat Service" : HTTP
"Gateway Service" --> "Message Service" : HTTP
"Gateway Service" --> "Notification Service" :  WebSocket

"Auth Service" --> "Auth DB"
"Chat Service" --> "Chat DB"
"Message Service" --> "Message DB"

"Auth Service" --> "Redis"
"Chat Service" --> "Redis"
"Message Service" --> "Redis"

"Message Service" --> "RabbitMQ"
"Notification Service" --> "RabbitMQ"

@enduml
