@startuml

class GatewayServer {
  run() : void
  registerRoutes() : void
}

class ProxyClient {
NetworkResponse forward(const RequestDTO &, const int port);
}

interface IClient {
  + NetworkResponse Get(const ForwardRequestDTO &)
  + NetworkResponse Delete(const ForwardRequestDTO &)
  + NetworkResponse Put(const ForwardRequestDTO &)
  + NetworkResponse Post(const ForwardRequestDTO &)
}

interface IVerifier
interface IRateLimiter {
  + allow(ip) : bool
}
interface IMetrics

interface IThreadPool {
  enqueu(lambda) : void
}

interface ISubscribeEvent {
  + subcrive(req) : void
}

interface IPublishEvent {
  + publish(req) : void
}

interface ICacheService
interface IEventBus

RabbitMQClient ..|> IEventBus

IEventBus ..|> ISubscribeEvent
IEventBus ..|> IPublishEvent
ThreadPool ..|> IThreadPool


GatewayApp *-- LoggingMiddleware
GatewayApp *-- RateLimitMiddleware
GatewayApp *-- MetricsMiddleware
GatewayApp *-- AuthMiddleware
GatewayApp *-- CacheMiddleware
GatewayServer *--> GatewayApp
GatewayServer o--> GatewayController

GatewayController o--> ICacheService
GatewayController o--> IThreadPool
GatewayController o--> IEventBus
GatewayController *--> ProxyClient
GatewayController o--> IClient
ProxyClient o--> IClient

AuthMiddleware o--> IVerifier
JWTVerifier ..|> IVerifier

CacheMiddleware o--> ICacheService
MetricsMiddleware o--> IMetrics
RateLimitMiddleware o--> IRateLimiter


GatewayMetrics ..|> IMetrics
RateLimiter ..|> IRateLimiter
RealHttpClient ..|> IClient

@enduml
