@startuml

class Server {
  + run() : void
}

class Controller {
  + updateMessage(req, message_id_str) : Response
  + deleteMessage(req, message_id_str) : Response
  + getMessageById(message_id_str) : Response
  + getMessagesFromChat(request_pack, chat_id_str) : Response
  + getReaction(request_pack, reaction_id_str) : Response
  + setup() : Response
}

interface IMessageCommandService {
  + saveMessage(message) : boo;
  + updateMessage(const Message &message);
  + deleteMessage(const Message &message);
  + saveMessageReaction(const Reaction &reaction);
  + deleteMessageReaction(const Reaction &reaction);
  + saveMessageReactionInfo(const std::vector<ReactionInfo> &reaction_infos);
}

interface IMessageQueryService {
  + getMessage(long long message_id);
  + getMessageStatus(long long message_id, long long receiver_id);
  + getChatMessages(const GetMessagePack &);
  + getUndeliveredMessages(long long user_id);
  + getMessagesStatus(const std::vector<Message> &messages, long long receiver_id);
  + getReadedMessageStatuses(long long message_id);
  + deleteMessageReaction(const Reaction &reaction);
  + getReactions(long long message_id, long long receiver_id);
  + getReactionInfo(long long message_reaction_id);
}


interface IRabitMQClient {
  + publish(publich_req) : void
  + subscribe(subscribe_req, EventCallback) : void
}

class RabbitMQClient {

}

interface IThreadPool {
}

class ThreadPool {
}

interface IIdGenerator {

}

interface IEventPublisher
interface IEventSubcriber

class QueuePublisher {
  + messageSaved(const Message& saved_message);
  + messageDeleted(const Message& deleted_message);
  + reactionDeleted(const Reaction& deleted_reaction);
  + reactionSaved(const Reaction& saved_reaction);
  + messageStatusSaved(const MessageStatus& saved_message_status);
}

class QueueSubscriber {
  + subscribeToSaveMessage(Callback);
  + subscribeToSaveMessageStatus(Callback);
  + subscribeToSaveMessageReaction(Callback);
  + subscribeToDeleteMessageReaction(Callback);
}

interface IEventBus

RabbitMQClient ..|> IEventBus

Server o--> Controller

IEventBus ..|> IEventPublisher
IEventBus ..|> IEventSubcriber

QueuePublisher o--> IEventPublisher
QueueSubscriber o--> IEventSubcriber

Controller ---> QueuePublisher
Controller ---> QueueSubscriber
Controller o--> IThreadPool
Controller o--> IMessageCommandService
Controller o--> IMessageQueryService


MessageCommandService ..|> IMessageCommandService
MessageCommandService o--> GenericRepository
MessageCommandService o--> IIdGenerator

MessageQueryService ..|> IMessageQueryService
MessageQueryService o--> ISqlExecutor
MessageQueryService o--> ICache
MessageQueryService --> QueryFactory

GenericRepository o--> ISqlExecutor
GenericRepository o--> ICache

GeneratorId ..|> IIdGenerator

ThreadPool ..|> IThreadPool



@enduml
