@startuml

class Server {
  + run() : void
}

interface IUserSocketRepository {
  + void saveConnections(UserId, SocketPtr socket);
  + void deleteConnections(SocketPtr conn);
  + SocketPtr getUserSocket(UserId);
  + bool userOnline(UserId);
}

interface ISocket {
  + void send_text(const std::string &text) override;
}


interface IActiveSocketRepository {
  + SocketPtr findSocket(crow::websocket::connection *conn);
  + void addConnection(const SocketPtr &socket)
  + void deleteConnection(const SocketPtr &socket)
}

interface IUserSocketRepository {
  + SocketPtr findSocket(crow::websocket::connection *conn);
  + void addConnection(const SocketPtr &socket)
  + void deleteConnection(const SocketPtr &socket)
}

class SocketRepository

interface IMessageHandler {
  void handle(const crow::json::rvalue &message, const std::shared_ptr<ISocket> &socket) override;
}

interface SocketHandlersRepository {
  + void handle()
}

interface ISubcriber {
  + subscribeAll() : void
}
class RabbitNotificationSubscriber

interface IPublisher {
    + saveMessageStatus(message_status) : void
    + saveDeliveryStatus(&msg, receiver_id) : void
    + saveReaction(reaction) : void
    + deleteReactio(reaction) : void
    + saveMessage(message) : void
}

class RabbitNotificationPublisher

interface INotifier {
 + notifyMember(user_id, json_message, type) : bool
}
class SocketNotifier {

}

interface INetworkFacade {
  + users() : IUserNetworkManager
  + messages() : IMessageNetworkManager
  + chats() : IChatsNetworkManager
}

interface IEventSubscriber {
  subscribe(SubscribeRequest, EventCallback) : void
}

interface IEventPublisher {
  publish(PublishRequest) : void
}

interface INetworkFacade

class NotificationOrchestrator {
  + onMessageStatusSaved(payload : str) : void
  + onMessageSaved(payload : str) : void
  + onMessageReactionDeleted(payload : str) : void
  + onMessageReactionSaved(payload : str) : void
  + onMessageDeleted(payload : str) : void
}

interface IUserNetworkManager {
  + getUserById(user_id) : optional_user
}

interface IMessageNetworkManager {
  + getChatIdOfMessage(message_id) : optional_chat_id
}

interface IChatsNetworkManager {
  + getMembersOfChat(chat_id) : std::vector<user_id>
}

interface IClient {
  + forward(req, port) : NetworkResponce
}


NetworkFacade ..|> INetworkFacade
NetworkFacade ..|> IUserNetworkManager
NetworkFacade ..|> IMessageNetworkManager
NetworkFacade ..|> IChatsNetworkManager

SocketNotifier ..|> INotifier
SocketNotifier o--> IUserSocketRepository

RabbitNotificationPublisher ..|> IPublisher
RabbitNotificationSubscriber ..|> ISubcriber

RabbitNotificationSubscriber o--> IEventSubscriber
RabbitNotificationSubscriber o--> NotificationOrchestrator
RabbitNotificationPublisher o--> IEventPublisher

IMessageHandler o--> ISocket

Server o--> SocketHandlersRepository
Server o--> IActiveSocketRepository
Server o--> ISubcriber

SocketHandlersRepository *--> IMessageHandler
SocketHandlersRepository o--> ISocket

NotificationOrchestrator o--> IPublisher
NotificationOrchestrator o--> INotifier
NotificationOrchestrator o--> INetworkFacade

CrowSocket ..|> ISocket
RabitMQClient ..|> IEventPublisher
RabitMQClient ..|> IEventSubscriber

SocketRepository ..|> IUserSocketRepository
SocketRepository ..|> IActiveSocketRepository
SocketRepository o--> ISocket

DeleteMessageReactionHandler ..|> IMessageHandler
InitMessageHandler ..|> IMessageHandler
MarkReadMessageHandler ..|> IMessageHandler
SaveMessageReactionHandler ..|> IMessageHandler
SendMessageHandler ..|> IMessageHandler

DeleteMessageReactionHandler o--> IPublisher
InitMessageHandler o--> IUserSocketRepository

UserNetworkManager ..|> IUserNetworkManager
MessageNetworkManager ..|> IMessageNetworkManager
ChatsNetworkManager ..|> IChatsNetworkManager

NetworkFacade --> UserNetworkManager
NetworkFacade --> MessageNetworkManager
NetworkFacade --> ChatsNetworkManager
NetworkFacade o--> ProxyClient

UserNetworkManager o--> ProxyClient
MessageNetworkManager o--> ProxyClient
ChatsNetworkManager o--> ProxyClient

ProxyClient o--> IClient
RealHttpClient ..|> IClient




@enduml
